Add empty env_variables.yaml to make deploy happy
Without it we get this error:

<pre>
ERROR: gcloud crashed (IncludeFileNotFound): File env_variables.yaml
listed in includes directive of
/home/travis/build/martbhell/wasthereannhlgamelastnight/src/app.yaml
could not be found.
</pre>

So now we have an empty file in the git repo and then we ignore it in
.gcloudignore so it shouldn't be uploaded (which would overwrite the
content that we do want it to contain)