Started on python3
Currently fails because webapp2 is crap bad?

Also my WSL ubuntu only has python3.5...

  File "/tmp/tmpM3YIZU/lib/python3.5/site-packages/webapp2.py", line 571
    except Exception, e:
                    ^
SyntaxError: invalid syntax