Send schedule updates to twitter (#11)
* Send schedule updates to twitter

We added some more logging earlier so also updated README with current
status around that.

For fixing #10 and adding some #twitter notifications:

Massive library import needed, could not add tweepy as a library: in
app.yaml and we are indeed running this on a static AppEngine:

https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27#vendoring

No _ssl module found (builtin to python) when running tweepy:

https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl

Setting environment variables involve deploying and not pushing the
env_variables.yml to github:

https://cloud.google.com/composer/docs/how-to/managing/environment-variables

Also we log that we tweeted and update cloud.md and mention env_variables in case we ever need to bootstrap this from scratch again / or change provider.

* Ignore env_variables.yaml in gcloud app deploy

* Add empty env_variables.yaml to make deploy happy

Without it we get this error:

<pre>
ERROR: gcloud crashed (IncludeFileNotFound): File env_variables.yaml
listed in includes directive of
/home/travis/build/martbhell/wasthereannhlgamelastnight/src/app.yaml
could not be found.
</pre>

So now we have an empty file in the git repo and then we ignore it in
.gcloudignore so it shouldn't be uploaded (which would overwrite the
content that we do want it to contain)

* The gcloud version was from 2017.10 last run

Let's try to update it..

* Let's use the commented out bit to update it..

ERROR: (gcloud.components.update) You cannot perform this action because
this Cloud SDK installation is managed by an external package manager.

* twitter link in banner

* retry 3 times